### ISSUE TITLE
LOAD control command is a default value, not an initial one.

### ISSUE THREAD

**Issue by ThomasAbballe** [Alneos/vega#23] opened 2019-07-16 15:37 UTC
Push c815f3d added a regression to the NASTRAN to SYSTUS parser. The control command LOAD, when outside the scope of an analysis, is a default option, and should be replaced by the next LOAD command (generally, an analysis dependent one). Instead it is treated as a supplementary load, meaning that some analysis have two loadings instead of one.
See TRUSS3-17 example, from the System-X base, for an example to this bug

**Comment by ldallolio** [comment] 2019-07-26 19:18
Fixed in 8ca82cdb1b9a5c6c0fd9f4cf57501427dfa88a9a TRUSS3-17 is passing. Problem was caused by a missing "trim()" in the first "LOAD " key. Added nastran_issue23_doubleload in NastranParser_test

**Closed as completed by ldallolio** 2019-07-26 19:18 UTC
Labels: bug
